apply plugin: "java"
version '1.0'
sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17
sourceSets.main.java.srcDirs = ["src"]
compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories{
    mavenCentral()
    maven{ url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven{ url 'https://www.jitpack.io' }
}
ext{
    //the build number that this plugin is made for
    mindustryVersion = 'v156'
    jabelVersion = "93fde537c7"
}

dependencies{
    compileOnly files("libs/server.jar")
    compileOnly files("libs/Mindustry.jar")
    compileOnly files("libs/dependencies.jar")
    // implementation 'org.mongodb:mongo-java-driver:3.12.7'
    compileOnly "com.github.Anuken.Mindustry:server:$mindustryVersion"
    implementation group: 'org.json', name: 'json', version: '20231013'
}
jar{
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "ServerHopper.jar"
    from{
        configurations.runtimeClasspath.collect{it.isDirectory() ? it : zipTree(it)}
    }
    from(rootDir){
        include "plugin.hjson"
    }
}

task downloadMindustryJars {
    doLast {
        def dir = file("libs")
        dir.mkdirs()

        def files = [
            [url: "https://github.com/Anuken/Mindustry/releases/download/v156.2/server-release.jar", name: "server.jar"],
            [url: "https://github.com/Anuken/Mindustry/releases/download/v156.2/Mindustry.jar", name: "Mindustry.jar"],
            [url: "https://github.com/Anuken/Mindustry/releases/download/v156.2/dependencies.jar", name: "dependencies.jar"]
        ]

        files.each {
            def f = new File(dir, it.name)
            if (!f.exists()) {
                new URL(it.url).withInputStream { i ->
                    f.withOutputStream { it2 -> it2 << i }
                }
            }
        }
    }
}
